export interface IBookingMatrixData {
  bookingMatrix: {
    timeInterval: { startHr: number; endHr: number }; //in minutes
    rooms: {
      id: string;
      name: string;
      displayName: string;
      slotSize: number;
      capacity: number;
      slots: {
        status: 'available' | 'unavailable' | 'booked' | 'pending';
        price: number;
      }[];
    }[];
  };
}

export async function fetchBookingMatrixData(): Promise<IBookingMatrixData> {
  return bookingMatrixMockData;
}

const bookingMatrixMockData: IBookingMatrixData = {
  bookingMatrix: {
    timeInterval: { startHr: 9, endHr: 24 },
    rooms: [
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 1',
        displayName: 'C1',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 2',
        displayName: 'C2',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 3',
        displayName: 'C3',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 4',
        displayName: 'C4',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 5',
        displayName: 'C5',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 1',
        displayName: 'C6',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 7',
        displayName: 'C7',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 8',
        displayName: 'C8',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '7b9793df-bd91-429f-8ea2-9c047bbbb27c',
        name: 'Court 9',
        displayName: 'C9',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'unavailable', price: 2450 },
          { status: 'unavailable', price: 2450 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'available', price: 2600 },
          { status: 'booked', price: 2100 },
          { status: 'booked', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
          { status: 'available', price: 2100 },
        ],
      },
      {
        id: '6939ef13-77d3-4c8b-89a6-8f5f8e17e718',
        name: 'Court 10',
        displayName: 'C10',
        slotSize: 30,
        capacity: 4,
        slots: [
          { status: 'available', price: 2500 },
          { status: 'available', price: 2500 },
          { status: 'booked', price: 2500 },
          { status: 'booked', price: 2500 },
          { status: 'available', price: 2500 },
          { status: 'available', price: 2500 },
          { status: 'booked', price: 2500 },
          { status: 'booked', price: 2500 },
          { status: 'available', price: 2500 },
        ],
      },
    ],
  },
};

// export interface IBookingMatrixData {
//   bookingMatrix: {
//     displayInterval: { start: number; end: number }; //time in minutes [start, end]
//     rooms: {
//       id: string;
//       name: string;
//       description: string;
//       capacity: number;
//       defaultPrice: number;
//       slotSize: number;
//       roomType: { id: string; name: string };
//       pricingPolicies: { price: number; mask: bigint }[];
//       availability: { mask: bigint };
//       bookedSlots: { mask: bigint };
//     }[];
//   };
// }

// export async function fetchBookingMatrixData(): Promise<IBookingMatrixData> {
//   return {
//     bookingMatrix: {
//       displayInterval: { start: 9 * 60, end: 24 * 60 },
//       rooms: [
//         {
//           id: '017420c6-4345-468d-8f5f-cb1b74bed19c',
//           name: 'court 1',
//           description: '',
//           capacity: 4,
//           defaultPrice: 24.0,
//           slotSize: 30,
//           roomType: { id: 'badminton', name: 'badminton' },
//           pricingPolicies: [],
//           availability: {
//             mask: BigInt(
//               '0b' + '11111111111111111111111111111000000000000000000',
//             ),
//           },
//           bookedSlots: { mask: BigInt('0b' + '00000000000000000000100011001') },
//         },
//         {
//           id: '8896940a-d422-46f4-82d8-cb7c105d25de',
//           name: 'court 2',
//           description: '',
//           capacity: 4,
//           defaultPrice: 24.0,
//           slotSize: 30,
//           roomType: { id: 'badminton', name: 'badminton' },
//           pricingPolicies: [],
//           availability: {
//             mask: BigInt(
//               '0b' + '00000000000000000011111111111111111111111111111',
//             ),
//           },
//           bookedSlots: { mask: BigInt('0b' + '00000000000000000000100011001') },
//         },
//         {
//           id: 'c74b0adf-1361-44c0-9628-89894fbc0c07',
//           name: 'court 3',
//           description: '',
//           capacity: 4,
//           defaultPrice: 24.0,
//           slotSize: 30,
//           roomType: { id: 'badminton', name: 'badminton' },
//           pricingPolicies: [],
//           availability: {
//             mask: BigInt(
//               '0b' + '00000000000000000011111111111111111111111111111',
//             ),
//           },
//           bookedSlots: { mask: BigInt('0b' + '00000000000000000000100011001') },
//         },
//         {
//           id: '72ff444d-4e0b-47b0-a57e-342bf57363a6',
//           name: 'court 4',
//           description: '',
//           capacity: 4,
//           defaultPrice: 24.0,
//           slotSize: 30,
//           roomType: { id: 'badminton', name: 'badminton' },
//           pricingPolicies: [],
//           availability: {
//             mask: BigInt(
//               '0b' + '00000000000000000011111111111111111111111111111',
//             ),
//           },
//           bookedSlots: { mask: BigInt('0b' + '00000000000000000000100011001') },
//         },
//         {
//           id: 'aaa204f9-a7db-4a31-9ebe-0392b487434b',
//           name: 'court 5',
//           description: '',
//           capacity: 4,
//           defaultPrice: 24.0,
//           slotSize: 30,
//           roomType: { id: 'badminton', name: 'badminton' },
//           pricingPolicies: [],
//           availability: {
//             mask: BigInt(
//               '0b' + '00000000000000000011111111111111111111111111111',
//             ),
//           },
//           bookedSlots: { mask: BigInt('0b' + '00000000000000000000100011001') },
//         },
//       ],
//     },
//   };
// }
