/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsLayoutImport } from './routes/settings/_layout'
import { Route as AuthSignupSuccessImport } from './routes/auth/signupSuccess'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthPasswordResetSuccessImport } from './routes/auth/passwordResetSuccess'
import { Route as AuthPasswordResetImport } from './routes/auth/passwordReset'
import { Route as AuthPasswordForgotSuccessImport } from './routes/auth/passwordForgotSuccess'
import { Route as AuthPasswordForgotImport } from './routes/auth/passwordForgot'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as SettingsLayoutIndexImport } from './routes/settings/_layout.index'
import { Route as BookingRoomTypeDateLayoutImport } from './routes/booking/$roomType.$date._layout'
import { Route as BookingRoomTypeDateLayoutIndexImport } from './routes/booking/$roomType.$date._layout.index'

// Create Virtual Routes

const SettingsImport = createFileRoute('/settings')()
const BookingRoomTypeDateImport = createFileRoute('/booking/$roomType/$date')()

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsLayoutRoute = SettingsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => SettingsRoute,
} as any)

const AuthSignupSuccessRoute = AuthSignupSuccessImport.update({
  id: '/auth/signupSuccess',
  path: '/auth/signupSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetSuccessRoute = AuthPasswordResetSuccessImport.update({
  id: '/auth/passwordResetSuccess',
  path: '/auth/passwordResetSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetRoute = AuthPasswordResetImport.update({
  id: '/auth/passwordReset',
  path: '/auth/passwordReset',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotSuccessRoute = AuthPasswordForgotSuccessImport.update({
  id: '/auth/passwordForgotSuccess',
  path: '/auth/passwordForgotSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotRoute = AuthPasswordForgotImport.update({
  id: '/auth/passwordForgot',
  path: '/auth/passwordForgot',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const BookingRoomTypeDateRoute = BookingRoomTypeDateImport.update({
  id: '/booking/$roomType/$date',
  path: '/booking/$roomType/$date',
  getParentRoute: () => rootRoute,
} as any)

const SettingsLayoutIndexRoute = SettingsLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsLayoutRoute,
} as any)

const BookingRoomTypeDateLayoutRoute = BookingRoomTypeDateLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => BookingRoomTypeDateRoute,
} as any)

const BookingRoomTypeDateLayoutIndexRoute =
  BookingRoomTypeDateLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookingRoomTypeDateLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgot': {
      id: '/auth/passwordForgot'
      path: '/auth/passwordForgot'
      fullPath: '/auth/passwordForgot'
      preLoaderRoute: typeof AuthPasswordForgotImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgotSuccess': {
      id: '/auth/passwordForgotSuccess'
      path: '/auth/passwordForgotSuccess'
      fullPath: '/auth/passwordForgotSuccess'
      preLoaderRoute: typeof AuthPasswordForgotSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordReset': {
      id: '/auth/passwordReset'
      path: '/auth/passwordReset'
      fullPath: '/auth/passwordReset'
      preLoaderRoute: typeof AuthPasswordResetImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordResetSuccess': {
      id: '/auth/passwordResetSuccess'
      path: '/auth/passwordResetSuccess'
      fullPath: '/auth/passwordResetSuccess'
      preLoaderRoute: typeof AuthPasswordResetSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/signupSuccess': {
      id: '/auth/signupSuccess'
      path: '/auth/signupSuccess'
      fullPath: '/auth/signupSuccess'
      preLoaderRoute: typeof AuthSignupSuccessImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/settings/_layout': {
      id: '/settings/_layout'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLayoutImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/_layout/': {
      id: '/settings/_layout/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsLayoutIndexImport
      parentRoute: typeof SettingsLayoutImport
    }
    '/booking/$roomType/$date': {
      id: '/booking/$roomType/$date'
      path: '/booking/$roomType/$date'
      fullPath: '/booking/$roomType/$date'
      preLoaderRoute: typeof BookingRoomTypeDateImport
      parentRoute: typeof rootRoute
    }
    '/booking/$roomType/$date/_layout': {
      id: '/booking/$roomType/$date/_layout'
      path: '/booking/$roomType/$date'
      fullPath: '/booking/$roomType/$date'
      preLoaderRoute: typeof BookingRoomTypeDateLayoutImport
      parentRoute: typeof BookingRoomTypeDateRoute
    }
    '/booking/$roomType/$date/_layout/': {
      id: '/booking/$roomType/$date/_layout/'
      path: '/'
      fullPath: '/booking/$roomType/$date/'
      preLoaderRoute: typeof BookingRoomTypeDateLayoutIndexImport
      parentRoute: typeof BookingRoomTypeDateLayoutImport
    }
  }
}

// Create and export the route tree

interface SettingsLayoutRouteChildren {
  SettingsLayoutIndexRoute: typeof SettingsLayoutIndexRoute
}

const SettingsLayoutRouteChildren: SettingsLayoutRouteChildren = {
  SettingsLayoutIndexRoute: SettingsLayoutIndexRoute,
}

const SettingsLayoutRouteWithChildren = SettingsLayoutRoute._addFileChildren(
  SettingsLayoutRouteChildren,
)

interface SettingsRouteChildren {
  SettingsLayoutRoute: typeof SettingsLayoutRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsLayoutRoute: SettingsLayoutRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface BookingRoomTypeDateLayoutRouteChildren {
  BookingRoomTypeDateLayoutIndexRoute: typeof BookingRoomTypeDateLayoutIndexRoute
}

const BookingRoomTypeDateLayoutRouteChildren: BookingRoomTypeDateLayoutRouteChildren =
  {
    BookingRoomTypeDateLayoutIndexRoute: BookingRoomTypeDateLayoutIndexRoute,
  }

const BookingRoomTypeDateLayoutRouteWithChildren =
  BookingRoomTypeDateLayoutRoute._addFileChildren(
    BookingRoomTypeDateLayoutRouteChildren,
  )

interface BookingRoomTypeDateRouteChildren {
  BookingRoomTypeDateLayoutRoute: typeof BookingRoomTypeDateLayoutRouteWithChildren
}

const BookingRoomTypeDateRouteChildren: BookingRoomTypeDateRouteChildren = {
  BookingRoomTypeDateLayoutRoute: BookingRoomTypeDateLayoutRouteWithChildren,
}

const BookingRoomTypeDateRouteWithChildren =
  BookingRoomTypeDateRoute._addFileChildren(BookingRoomTypeDateRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/settings': typeof SettingsLayoutRouteWithChildren
  '/settings/': typeof SettingsLayoutIndexRoute
  '/booking/$roomType/$date': typeof BookingRoomTypeDateLayoutRouteWithChildren
  '/booking/$roomType/$date/': typeof BookingRoomTypeDateLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/settings': typeof SettingsLayoutIndexRoute
  '/booking/$roomType/$date': typeof BookingRoomTypeDateLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/_layout': typeof SettingsLayoutRouteWithChildren
  '/settings/_layout/': typeof SettingsLayoutIndexRoute
  '/booking/$roomType/$date': typeof BookingRoomTypeDateRouteWithChildren
  '/booking/$roomType/$date/_layout': typeof BookingRoomTypeDateLayoutRouteWithChildren
  '/booking/$roomType/$date/_layout/': typeof BookingRoomTypeDateLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/settings'
    | '/settings/'
    | '/booking/$roomType/$date'
    | '/booking/$roomType/$date/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/settings'
    | '/booking/$roomType/$date'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/settings'
    | '/settings/_layout'
    | '/settings/_layout/'
    | '/booking/$roomType/$date'
    | '/booking/$roomType/$date/_layout'
    | '/booking/$roomType/$date/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordForgotSuccessRoute: typeof AuthPasswordForgotSuccessRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthPasswordResetSuccessRoute: typeof AuthPasswordResetSuccessRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  BookingRoomTypeDateRoute: typeof BookingRoomTypeDateRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordForgotSuccessRoute: AuthPasswordForgotSuccessRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthPasswordResetSuccessRoute: AuthPasswordResetSuccessRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
  SettingsRoute: SettingsRouteWithChildren,
  BookingRoomTypeDateRoute: BookingRoomTypeDateRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/passwordForgot",
        "/auth/passwordForgotSuccess",
        "/auth/passwordReset",
        "/auth/passwordResetSuccess",
        "/auth/signup",
        "/auth/signupSuccess",
        "/settings",
        "/booking/$roomType/$date"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/passwordForgot": {
      "filePath": "auth/passwordForgot.tsx"
    },
    "/auth/passwordForgotSuccess": {
      "filePath": "auth/passwordForgotSuccess.tsx"
    },
    "/auth/passwordReset": {
      "filePath": "auth/passwordReset.tsx"
    },
    "/auth/passwordResetSuccess": {
      "filePath": "auth/passwordResetSuccess.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/auth/signupSuccess": {
      "filePath": "auth/signupSuccess.tsx"
    },
    "/settings": {
      "filePath": "settings",
      "children": [
        "/settings/_layout"
      ]
    },
    "/settings/_layout": {
      "filePath": "settings/_layout.tsx",
      "parent": "/settings",
      "children": [
        "/settings/_layout/"
      ]
    },
    "/settings/_layout/": {
      "filePath": "settings/_layout.index.tsx",
      "parent": "/settings/_layout"
    },
    "/booking/$roomType/$date": {
      "filePath": "booking",
      "children": [
        "/booking/$roomType/$date/_layout"
      ]
    },
    "/booking/$roomType/$date/_layout": {
      "filePath": "booking/$roomType.$date._layout.tsx",
      "parent": "/booking/$roomType/$date",
      "children": [
        "/booking/$roomType/$date/_layout/"
      ]
    },
    "/booking/$roomType/$date/_layout/": {
      "filePath": "booking/$roomType.$date._layout.index.tsx",
      "parent": "/booking/$roomType/$date/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
