/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignupSuccessImport } from './routes/auth/signupSuccess'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthPasswordResetSuccessImport } from './routes/auth/passwordResetSuccess'
import { Route as AuthPasswordResetImport } from './routes/auth/passwordReset'
import { Route as AuthPasswordForgotSuccessImport } from './routes/auth/passwordForgotSuccess'
import { Route as AuthPasswordForgotImport } from './routes/auth/passwordForgot'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as settingsSettingsImport } from './routes/(settings)/settings'
import { Route as homeHomeImport } from './routes/(home)/home'
import { Route as bookingBookingImport } from './routes/(booking)/booking'
import { Route as settingsSettingsIndexImport } from './routes/(settings)/settings.index'
import { Route as homeHomeIndexImport } from './routes/(home)/home.index'
import { Route as bookingBookingRoomTypeDateImport } from './routes/(booking)/booking.$roomType.$date'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupSuccessRoute = AuthSignupSuccessImport.update({
  id: '/auth/signupSuccess',
  path: '/auth/signupSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetSuccessRoute = AuthPasswordResetSuccessImport.update({
  id: '/auth/passwordResetSuccess',
  path: '/auth/passwordResetSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetRoute = AuthPasswordResetImport.update({
  id: '/auth/passwordReset',
  path: '/auth/passwordReset',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotSuccessRoute = AuthPasswordForgotSuccessImport.update({
  id: '/auth/passwordForgotSuccess',
  path: '/auth/passwordForgotSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotRoute = AuthPasswordForgotImport.update({
  id: '/auth/passwordForgot',
  path: '/auth/passwordForgot',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const settingsSettingsRoute = settingsSettingsImport.update({
  id: '/(settings)/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const homeHomeRoute = homeHomeImport.update({
  id: '/(home)/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const bookingBookingRoute = bookingBookingImport.update({
  id: '/(booking)/booking',
  path: '/booking',
  getParentRoute: () => rootRoute,
} as any)

const settingsSettingsIndexRoute = settingsSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => settingsSettingsRoute,
} as any)

const homeHomeIndexRoute = homeHomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeHomeRoute,
} as any)

const bookingBookingRoomTypeDateRoute = bookingBookingRoomTypeDateImport.update(
  {
    id: '/$roomType/$date',
    path: '/$roomType/$date',
    getParentRoute: () => bookingBookingRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(booking)/booking': {
      id: '/(booking)/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof bookingBookingImport
      parentRoute: typeof rootRoute
    }
    '/(home)/home': {
      id: '/(home)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof homeHomeImport
      parentRoute: typeof rootRoute
    }
    '/(settings)/settings': {
      id: '/(settings)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof settingsSettingsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgot': {
      id: '/auth/passwordForgot'
      path: '/auth/passwordForgot'
      fullPath: '/auth/passwordForgot'
      preLoaderRoute: typeof AuthPasswordForgotImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgotSuccess': {
      id: '/auth/passwordForgotSuccess'
      path: '/auth/passwordForgotSuccess'
      fullPath: '/auth/passwordForgotSuccess'
      preLoaderRoute: typeof AuthPasswordForgotSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordReset': {
      id: '/auth/passwordReset'
      path: '/auth/passwordReset'
      fullPath: '/auth/passwordReset'
      preLoaderRoute: typeof AuthPasswordResetImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordResetSuccess': {
      id: '/auth/passwordResetSuccess'
      path: '/auth/passwordResetSuccess'
      fullPath: '/auth/passwordResetSuccess'
      preLoaderRoute: typeof AuthPasswordResetSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/signupSuccess': {
      id: '/auth/signupSuccess'
      path: '/auth/signupSuccess'
      fullPath: '/auth/signupSuccess'
      preLoaderRoute: typeof AuthSignupSuccessImport
      parentRoute: typeof rootRoute
    }
    '/(home)/home/': {
      id: '/(home)/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof homeHomeIndexImport
      parentRoute: typeof homeHomeImport
    }
    '/(settings)/settings/': {
      id: '/(settings)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof settingsSettingsIndexImport
      parentRoute: typeof settingsSettingsImport
    }
    '/(booking)/booking/$roomType/$date': {
      id: '/(booking)/booking/$roomType/$date'
      path: '/$roomType/$date'
      fullPath: '/booking/$roomType/$date'
      preLoaderRoute: typeof bookingBookingRoomTypeDateImport
      parentRoute: typeof bookingBookingImport
    }
  }
}

// Create and export the route tree

interface bookingBookingRouteChildren {
  bookingBookingRoomTypeDateRoute: typeof bookingBookingRoomTypeDateRoute
}

const bookingBookingRouteChildren: bookingBookingRouteChildren = {
  bookingBookingRoomTypeDateRoute: bookingBookingRoomTypeDateRoute,
}

const bookingBookingRouteWithChildren = bookingBookingRoute._addFileChildren(
  bookingBookingRouteChildren,
)

interface homeHomeRouteChildren {
  homeHomeIndexRoute: typeof homeHomeIndexRoute
}

const homeHomeRouteChildren: homeHomeRouteChildren = {
  homeHomeIndexRoute: homeHomeIndexRoute,
}

const homeHomeRouteWithChildren = homeHomeRoute._addFileChildren(
  homeHomeRouteChildren,
)

interface settingsSettingsRouteChildren {
  settingsSettingsIndexRoute: typeof settingsSettingsIndexRoute
}

const settingsSettingsRouteChildren: settingsSettingsRouteChildren = {
  settingsSettingsIndexRoute: settingsSettingsIndexRoute,
}

const settingsSettingsRouteWithChildren =
  settingsSettingsRoute._addFileChildren(settingsSettingsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof bookingBookingRouteWithChildren
  '/home': typeof homeHomeRouteWithChildren
  '/settings': typeof settingsSettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/home/': typeof homeHomeIndexRoute
  '/settings/': typeof settingsSettingsIndexRoute
  '/booking/$roomType/$date': typeof bookingBookingRoomTypeDateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof bookingBookingRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/home': typeof homeHomeIndexRoute
  '/settings': typeof settingsSettingsIndexRoute
  '/booking/$roomType/$date': typeof bookingBookingRoomTypeDateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(booking)/booking': typeof bookingBookingRouteWithChildren
  '/(home)/home': typeof homeHomeRouteWithChildren
  '/(settings)/settings': typeof settingsSettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
  '/(home)/home/': typeof homeHomeIndexRoute
  '/(settings)/settings/': typeof settingsSettingsIndexRoute
  '/(booking)/booking/$roomType/$date': typeof bookingBookingRoomTypeDateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/home'
    | '/settings'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/home/'
    | '/settings/'
    | '/booking/$roomType/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/home'
    | '/settings'
    | '/booking/$roomType/$date'
  id:
    | '__root__'
    | '/'
    | '/(booking)/booking'
    | '/(home)/home'
    | '/(settings)/settings'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
    | '/(home)/home/'
    | '/(settings)/settings/'
    | '/(booking)/booking/$roomType/$date'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  bookingBookingRoute: typeof bookingBookingRouteWithChildren
  homeHomeRoute: typeof homeHomeRouteWithChildren
  settingsSettingsRoute: typeof settingsSettingsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordForgotSuccessRoute: typeof AuthPasswordForgotSuccessRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthPasswordResetSuccessRoute: typeof AuthPasswordResetSuccessRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  bookingBookingRoute: bookingBookingRouteWithChildren,
  homeHomeRoute: homeHomeRouteWithChildren,
  settingsSettingsRoute: settingsSettingsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordForgotSuccessRoute: AuthPasswordForgotSuccessRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthPasswordResetSuccessRoute: AuthPasswordResetSuccessRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(booking)/booking",
        "/(home)/home",
        "/(settings)/settings",
        "/auth/login",
        "/auth/passwordForgot",
        "/auth/passwordForgotSuccess",
        "/auth/passwordReset",
        "/auth/passwordResetSuccess",
        "/auth/signup",
        "/auth/signupSuccess"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(booking)/booking": {
      "filePath": "(booking)/booking.tsx",
      "children": [
        "/(booking)/booking/$roomType/$date"
      ]
    },
    "/(home)/home": {
      "filePath": "(home)/home.tsx",
      "children": [
        "/(home)/home/"
      ]
    },
    "/(settings)/settings": {
      "filePath": "(settings)/settings.tsx",
      "children": [
        "/(settings)/settings/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/passwordForgot": {
      "filePath": "auth/passwordForgot.tsx"
    },
    "/auth/passwordForgotSuccess": {
      "filePath": "auth/passwordForgotSuccess.tsx"
    },
    "/auth/passwordReset": {
      "filePath": "auth/passwordReset.tsx"
    },
    "/auth/passwordResetSuccess": {
      "filePath": "auth/passwordResetSuccess.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/auth/signupSuccess": {
      "filePath": "auth/signupSuccess.tsx"
    },
    "/(home)/home/": {
      "filePath": "(home)/home.index.tsx",
      "parent": "/(home)/home"
    },
    "/(settings)/settings/": {
      "filePath": "(settings)/settings.index.tsx",
      "parent": "/(settings)/settings"
    },
    "/(booking)/booking/$roomType/$date": {
      "filePath": "(booking)/booking.$roomType.$date.tsx",
      "parent": "/(booking)/booking"
    }
  }
}
ROUTE_MANIFEST_END */
