/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignupSuccessImport } from './routes/auth/signupSuccess'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthPasswordResetSuccessImport } from './routes/auth/passwordResetSuccess'
import { Route as AuthPasswordResetImport } from './routes/auth/passwordReset'
import { Route as AuthPasswordForgotSuccessImport } from './routes/auth/passwordForgotSuccess'
import { Route as AuthPasswordForgotImport } from './routes/auth/passwordForgot'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupSuccessRoute = AuthSignupSuccessImport.update({
  id: '/auth/signupSuccess',
  path: '/auth/signupSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetSuccessRoute = AuthPasswordResetSuccessImport.update({
  id: '/auth/passwordResetSuccess',
  path: '/auth/passwordResetSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetRoute = AuthPasswordResetImport.update({
  id: '/auth/passwordReset',
  path: '/auth/passwordReset',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotSuccessRoute = AuthPasswordForgotSuccessImport.update({
  id: '/auth/passwordForgotSuccess',
  path: '/auth/passwordForgotSuccess',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotRoute = AuthPasswordForgotImport.update({
  id: '/auth/passwordForgot',
  path: '/auth/passwordForgot',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgot': {
      id: '/auth/passwordForgot'
      path: '/auth/passwordForgot'
      fullPath: '/auth/passwordForgot'
      preLoaderRoute: typeof AuthPasswordForgotImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordForgotSuccess': {
      id: '/auth/passwordForgotSuccess'
      path: '/auth/passwordForgotSuccess'
      fullPath: '/auth/passwordForgotSuccess'
      preLoaderRoute: typeof AuthPasswordForgotSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordReset': {
      id: '/auth/passwordReset'
      path: '/auth/passwordReset'
      fullPath: '/auth/passwordReset'
      preLoaderRoute: typeof AuthPasswordResetImport
      parentRoute: typeof rootRoute
    }
    '/auth/passwordResetSuccess': {
      id: '/auth/passwordResetSuccess'
      path: '/auth/passwordResetSuccess'
      fullPath: '/auth/passwordResetSuccess'
      preLoaderRoute: typeof AuthPasswordResetSuccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/signupSuccess': {
      id: '/auth/signupSuccess'
      path: '/auth/signupSuccess'
      fullPath: '/auth/signupSuccess'
      preLoaderRoute: typeof AuthSignupSuccessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordForgot': typeof AuthPasswordForgotRoute
  '/auth/passwordForgotSuccess': typeof AuthPasswordForgotSuccessRoute
  '/auth/passwordReset': typeof AuthPasswordResetRoute
  '/auth/passwordResetSuccess': typeof AuthPasswordResetSuccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signupSuccess': typeof AuthSignupSuccessRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/passwordForgot'
    | '/auth/passwordForgotSuccess'
    | '/auth/passwordReset'
    | '/auth/passwordResetSuccess'
    | '/auth/signup'
    | '/auth/signupSuccess'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordForgotSuccessRoute: typeof AuthPasswordForgotSuccessRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthPasswordResetSuccessRoute: typeof AuthPasswordResetSuccessRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSignupSuccessRoute: typeof AuthSignupSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordForgotSuccessRoute: AuthPasswordForgotSuccessRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthPasswordResetSuccessRoute: AuthPasswordResetSuccessRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSignupSuccessRoute: AuthSignupSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/passwordForgot",
        "/auth/passwordForgotSuccess",
        "/auth/passwordReset",
        "/auth/passwordResetSuccess",
        "/auth/signup",
        "/auth/signupSuccess"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/passwordForgot": {
      "filePath": "auth/passwordForgot.tsx"
    },
    "/auth/passwordForgotSuccess": {
      "filePath": "auth/passwordForgotSuccess.tsx"
    },
    "/auth/passwordReset": {
      "filePath": "auth/passwordReset.tsx"
    },
    "/auth/passwordResetSuccess": {
      "filePath": "auth/passwordResetSuccess.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/auth/signupSuccess": {
      "filePath": "auth/signupSuccess.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
